name: build-latest
on:
  push:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_DOWNLOADS_DEV_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_DOWNLOADS_DEV_SECRET_KEY }}
  AWS_REGION: us-east-1
  BUILD_DIR: /home/runner/work/mcp-alkira/mcp-alkira
  BUILD_ARTIFACTS_PATH: s3://downloads.alkira.com/dev/mcp-alkira/latest
  CGO_ENABLED: 0

jobs:
  latest:
    name: latest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          cd ${{ env.BUILD_DIR }}
          ver=`git describe`
          echo "latest_version=$ver" >> $GITHUB_ENV
          make release

      - name: Upload to S3 latest directory
        run: |
          aws s3 rm "${{ env.BUILD_ARTIFACTS_PATH }}/" --recursive
          aws s3 cp releases/${{ env.latest_version }} "${{ env.BUILD_ARTIFACTS_PATH }}/" --recursive
